#!/bin/csh

# The normal expectation is that all of this is installed in
#          /FPT   
# If not, you will have to edit this script to reflect where
# you really installed it.


set rlist = ""
set Ilist = ""


foreach ncarg ($argv[*])

  switch ($ncarg)

   case *.c :
    # do nothing if it is a .c file
   breaksw

   case -I* :
    set Ilist = ($Ilist $ncarg)
   breaksw

   default :
    set rlist = ($rlist  $ncarg)

   breaksw

  endsw

end


#echo "Ilist = " $Ilist
#echo "rlist = " $rlist






foreach cfile ($argv[*])

  switch ($cfile)

   case *.c :

# this sed script edits your source code to allow for doubles
# to serve as array subscripts

     sed     -f  /FPT/sed.control <   $cfile   >  $cfile.drawM.345ab29.c


#turn on optimization wtih -O1
#     cc -O1  -c  -I/FPT/Source  $Ilist   $cfile.drawM.345ab29.c  
#     cc   -c -m32  -I/FPT/Source  $Ilist   $cfile.drawM.345ab29.c  
      cc   -c   -I/FPT/Source  $Ilist   $cfile.drawM.345ab29.c  


   breaksw

  endsw

end




#cc  -O1  /FPT/Dotos/*.o    *drawM.345ab29.o  $rlist   -L/usr/X11R6/lib -lm -lX11 -lXext

# cc   -m32 /FPT/Dotos/*.o    *drawM.345ab29.o  $rlist   -L/usr/X11R6/lib -lm -lX11 -lXext

cc   /FPT/Dotos/*.o    *drawM.345ab29.o  $rlist   -L/usr/X11R6/lib -lm -lX11 -lXext


\rm    *drawM.345ab29.*

