#!/bin/bash

# The normal expectation is that all of this is installed in
#          /FPT   
# If not, you will have to edit this script to reflect where
# you really installed it.


clist=""

for name in $@; do

  bname=" $name"
  clist=("$clist""$bname")

done

#echo $clist

cc  -I./Source -I./HeadersC /Users/nick/Downloads/FPT/DotosC/*.o    $clist   -L/usr/X11R6/lib -I/usr/X11R6/include -lm -lX11 -lXext




