#!/bin/bash

# The normal expectation is that all of this is installed in
#          /FPT   
# If not, you will have to edit this script to reflect where
# you really installed it.


rlist=""
Ilist=""
tlist=""


for name in $@; do

  bname=" $name"
#  echo "bname = ^""$bname""^"
#  echo "name = ^"$name"^"
#  tlist=("$tlist""$bname")
#  echo "tlist = ^"$tlist"^"

  case $name in
    *.c)
    # do nothing if it is a .c file
      ;;
    -I*)
    Ilist=("$Ilist""$bname")
      ;;
    *)
    rlist=("$rlist""$bname")
      ;;

  esac

done



#echo "Ilist = " $Ilist
#echo "rlist = " $rlist



for cfile in $@; do


  case $cfile in
    *.c)

     cp  $cfile  $cfile.temp878ab89.c ;
     cc  -c   -I/FPT/Source  $Ilist   $cfile.temp878ab89.c

      ;;
    *)
      ;;

  esac

done



cc  /FPT/Dotos/*.o    *temp878ab89.o  $rlist   -L/usr/X11R6/lib -lm -lX11 -lXext
\rm   *temp878ab89*

